# .air.toml

root = "."
tmp_dir = "tmp"

[build]
# Build the server entrypoint
cmd = "go build -o tmp/main ./cmd/server"
bin = "tmp/main"

# Ignore unnecessary dirs
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_file = []
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
